---
- hosts: all
  become: yes

  tasks:
    - name: Test connection
      ping:

  roles:
    - common
    - docker

- hosts: master
  become: yes

  roles:
  - consul

- hosts: node
  become: yes

  roles:
  - consul
