---
- hosts: all
  become: yes

  tasks:
    - name: Test connection
      ping:

  roles:
    - common
    - docker

- hosts: controller
  become: yes

  tasks:
  - iptables:
      chain: FORWARD
      policy: ACCEPT

- hosts: controller:p
  become: yes

  roles:
  - consul
  - nomad

- hosts: node
  become: yes

  roles:
  - consul
  - nomad

