---
- name: Install list of packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg: "{{item}}"
    state: present
    autoremove: yes
  with_items:
   - unzip
#   - apt-transport-https
#   - ca-certificates
#   - curl
#   - gnupg2
#   - software-properties-common

- name   : "main | including hostname.yml"
  import_tasks : "hostname.yml"

- name   : "main | including device-init.yml"
  import_tasks : "device-init.yml"

