---

- name: Get the Docker signing key for packages
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add the Docker official repos
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian stretch stable
    update_cache: yes
    state: present

- name: Remove the main Docker official repos
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian stretch main
    update_cache: yes
    state: absent

- name: Install docker-ce package
  apt:
    pkg: docker-ce
    update_cache: yes
    cache_valid_time: 3600
    state: present
    autoremove: yes

- name: Enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes